#!/bin/bash
# -*- coding: utf-8 -*-
# copyright (c): 2019 Tony Aldon <aldon.tony@gmail.com>
# License: MIT

# remove some files
for dir in `ls tex`; do
		if [[ -d tex/$dir ]]; then
			 rm tex/$dir/*.aux;
			 rm tex/$dir/*.log;
			 rm tex/$dir/*.out;
		fi
done;
		
